### PR TITLE
Bp 53/feat/join multiple tables

### PR DESCRIPTION
**Pull request by mayankgituni**

### CODE REVIEW

**Comment by jay1805** [comment]
Hey @mayankgituni, the codeclimate checks are just in regards to tests right?

Other than that, everything seems good to me!

**Comment by l-trethewey** [comment]
Apart from the test coverage issues, it looks good to me too, but I'm not entirely sure what we should do here.

**Comment by mayankgituni** [comment]
> Apart from the test coverage issues, it looks good to me too, but I'm not entirely sure what we should do here.

Test coverage is failing because I didn't push the unit test with the code. It should be fine I am going to do it in my next tasks anyway. Just comment and mark the PR reviewed.

**Comment by mayankgituni** [comment]
> Hey @mayankgituni, the codeclimate checks are just in regards to tests right?
> 
> Other than that, everything seems good to me!

I think it should be fine for now. I am going to push the uni test in my next PR it should resolve then.

**Pull request merged**
